# Get the AACN01 bulletins
 
broker amqps://anonymous:anonymous@dd.weather.gc.ca/

# Using HPFX:
# broker amqps://anonymous:anonymous@hpfx.collab.science.gc.ca

subtopic *.WXO-DD.bulletins.alphanumeric.*.AA.CWAO.#

# expire, in operations should be longer than longest expected interruption
# lifetime of the queue on the server. For operational use, increase to 1d (1jour)
expire 10m
 
# instances, number of download processes to run. function of latency and bandwidth.
# increase if you see lag.
instances 2

# only accept files matching the accept statement below, ignore others
# accepter uniquement les fichiers correspondant à l'instruction accept ci-dessous, ignorer les autres
acceptUnmatched False

mirror True 

directory /tmp/
accept .*AACN01.*
