# Get the XML Citypage files
# For more information about this product, please consult the documentation at 
#  https://eccc-msc.github.io/open-data/msc-data/citypage-weather/readme_citypageweather_en/

# Télécharger le fichiers XML Citypage
# Pour plus d'information sur ce produit, veuillez consulter la documentation a
#  https://eccc-msc.github.io/open-data/msc-data/citypage-weather/readme_citypageweather_fr/

broker amqps://dd.weather.gc.ca/
topicPrefix v02.post

# instances, number of download processes to run. function of latency and bandwidth.
# increase if you see lag.
#   quantité de téléchargement en parralèle.  En cas de délai de livraison, augmentez.
instances 2

# expire, in operations should be longer than longest expected interruption
#   durée de vie du file d´attente sur le serveur.  Pour usage opérationnel, augmentez a 1d (1 jour.)
expire 10m

subtopic *.WXO-DD.citypage_weather.AB.*
subtopic *.WXO-DD.citypage_weather.BC.*
subtopic *.WXO-DD.citypage_weather.HEF.*
subtopic *.WXO-DD.citypage_weather.MB.*
subtopic *.WXO-DD.citypage_weather.NB.*
subtopic *.WXO-DD.citypage_weather.NL.*
subtopic *.WXO-DD.citypage_weather.NS.*
subtopic *.WXO-DD.citypage_weather.NT.*
subtopic *.WXO-DD.citypage_weather.NU.*
subtopic *.WXO-DD.citypage_weather.ON.*
subtopic *.WXO-DD.citypage_weather.PE.*
subtopic *.WXO-DD.citypage_weather.QC.*
subtopic *.WXO-DD.citypage_weather.SK.*
subtopic *.WXO-DD.citypage_weather.YT.*

directory /tmp/citypage
mirror True
