FROM ubuntu:latest

LABEL maintainer="ssc.sscdatarouting-spcroutagededonnees.spc@ssc-spc.gc.ca"

ENV TZ="Etc/UTC" \
    DEBIAN_FRONTEND="noninteractive" \
    BUILD_PACKAGES="build-essential" 

# deps copied from setup.py requires= and debian/control

RUN apt-get update ; apt-get install -y python3-amqp python3-appdirs python3-dateparser python3-humanfriendly python3-humanize python3-jsonpickle python3-netifaces python3-paho-mqtt python3-paramiko python3-pip python3-psutil python3-watchdog  
