@startuml
participant ":hb_memory.Hb_Memory" as hb
participant "parent:sr_watch.sr_watch" as w1
participant ":sr_watch" as wm
participant ":sr_watch.sr_watch" as w2

[o-> hb: restart()
 activate hb
 hb -> w1: run_command(cmd)
  note right
   using subprocess.run(cmd)
   cmd: 'sr_watch --no 1 f40.conf restart'
  end note
  activate w1
  w1 -> wm: main()
   activate wm
   create w2
   wm -> w2
   wm -> w2: exec_action(action, old)
    activate w2
    w2 -> w2: restart_parent
     activate w2
     w2 -> w2: build_instance(no)
      activate w2
      return
     w2 -> w2: restart_instance()
      activate w2
      w2 -> w2: stop_instance()
       activate w2
       loop stillAlive && can_sleep
        w2 -> os: kill(pid, SIGTERM)
         activate os
         return
       end loop
       alt stillAlive
        w2 -> os: kill(pid, SIGKILL)
         activate os
         return
       end alt
       return
      w2 -> w2: start_instance()
       activate w2
       return
      alt pid
       w2 -> w2: stop_instance()
        activate w2
        return
      end alt
      note right of w2: Prepare cmd for win32
      note right of w2: Prepare cmd args
      note right of w2: subprocess.Popen(cmd)
      return
     return
    return
   return
  return
[O<- hb
deactivate hb
@enduml