@startuml
participant ":sr_watch.sr_watch" as w1
participant "post_hc:sr_amqp.HostConnect" as hc
participant "plugin:Post_Total" as p
participant "cache:sr_cache.sr_cache" as sc
participant "observer:Observer" as obs

[o->> w1: stop_signal(signum, stack)
 activate w1
 note left: using the signal callback
 w1 -> w1: stop()
 activate w1
 w1 -> w1: close()
 activate w1
 loop on_stop_list && plugin_break
  w1 -> p: plugin(parent)
  activate p
  return
 end loop
 alt post_hc
  w1 -> hc: close()
  activate hc
  return
  destroy hc
 end alt
 alt cache
  w1 -> sc: close()
  activate sc
  return
  destroy sc
 end alt
 alt sleep && obs_watched
  loop ow in obs_watched
   w1 -> obs: unschedule(ow)
   activate obs
   return
  end loop
  w1 -> obs: stop()
  activate obs
  return
  destroy obs
 end alt
 return
 return
 w1 -> os: _exit(0)
 activate os
 w1 <<-- os:
 deactivate os
 deactivate w1
 destroy w1
<- w1

@enduml