@startuml
participant ":sr_subscribe.sr_subscribe" as ss
participant "plugin:hb_memory.Hb_Memory" as hbm
participant "plugin:hb_pulse.Hb_pulse" as hbp
participant "plugin:hb_retry.RETRY" as hbr
participant "parent.consumer.retry:sr_retry.sr_retry" as sr

''''''Heartbeat run''''''
[o-> ss: run()
loop true
 activate ss
 ss -> ss: heartbeat_check()
  activate ss
  alt elapsed > last_heartbeat
   ss -> ss: ____on_heartbeat____()
    activate ss
     ss -> hbm: on_heartbeat(parent)
      activate hbm
      return
     ss -> hbp: on_heartbeat(parent)
      activate hbp
      return
     ss -> hbr: on_heartbeat(parent)
      activate hbr
      hbr -> sr: on_heartbeat(parent)
       activate sr
       loop msg_list X 3 (state, retry, new)
        sr -> sr: msg_get_from_file(work)
         activate sr
         sr -> sr: msgFromJson(line)
          activate sr
          return msg
         return fp, msg
        sr -> sr: msg_append_to_file(work)
         activate sr
         sr -> sr: msgToJson(line)
         return heart_fp
       end loop
        alt N == 0
         sr -> sr: os.unlink(heart_path)
         activate sr
         return
        end alt
      return
    return True
  end alt
  return True
 return
end loop
[<--o ss
deactivate ss
@enduml