@startuml
skinparam Interface {
 BackgroundColor<<mqtt(s)>> blue
}

:Sarra User: as su
:Partner User: as pu

together {
 Node "Sarracenia" as s128 {
  component "MQTT Client" as 128
  note left of 128: Issue 128
 }
 Node "Sarracenia" as s227 {
  component "RabbitMQTT Client" as 227
  note right of 227: Issue 227
 }
}

Interface " " <<amqp(s)>> as amqp

together {
 Interface " " <<mqtt(s)>> as mqtt1
 Interface " " <<mqtt(s)>> as mqtt2
 Node "RabbitMQ Broker" as rmq {
  component "MQTT Plugin" {
   component "rabbitmqtt exchange" as rex
  }
 }
}

Node "MQTT Broker" as mbrk
Node "MQTT Client" as mcl

su --> s128
su --> s227
pu --> mcl
amqp -- rmq
mqtt1 -- rmq
mcl <-- mqtt1: from
mcl --> mqtt1: to
s128 <-- mqtt2: from
s128 --> mqtt2: to
s227 <-- amqp: from
s227 --> amqp: to
mqtt2 -- mbrk
mcl <-- mqtt2: from
mcl --> mqtt2: to

@enduml

