@startuml

class "RabbitMqtt" as rm {
 is_activated
 exchange
 user
 message
}
class "Configuration" as scfg {
 is_rabbitmqtt_enable
 is_post_rabbitmqtt_enable
 broker
 exchange
 post_broker
 post_exchange
 accept
}
class "RabbitMqttTopic" as rmt {
 exchange_prefix
 accept_suffix
}
class "Message" as sm {
 version = "v02"
}
class "Consumer" as c {

}
class "Publisher" as p {

}

c --> rm: subscribe-to
c --> rm: consume-from

sc -> scfg: uses
@enduml

