@startuml

:Partner User: as user
:Sarra User: as su

note top of s128: Issue 128
Node "Sarracenia" as s128 {
 component "mqtt" as 128
}

note top of s227: Issue 227
Node "Sarracenia" as s227 {
 component "rabbitmqtt" as 227
}
Node "RabbitMQ Broker" as rmq {
 component "MQTT Plugin" {
  component "rabbitmqtt exchange" as rex
 }
}

Node "MQTT Broker" as mbrk
Node "MQTT Client" as mcl

su --> s227
su --> s128
user -u-> mcl
s227 <--> rmq: amqp(s)://
s128 <--> mbrk: mqtt(s)://
mcl <-u-> mbrk: mqtt(s)://
mcl <-u-> rmq: mqtt(s)://

@enduml

