@startuml
sprite $exchange [16x16/16] {
00000FFFFF00000
000FFFFFFFFF000
00FFFFFFFF0FF00
0FFFFFFFFF00FF0
FF00000000000FF
FFFFFFFFFFFFFFF
FF00000000000FF
0FF00FFFFFFFFF0
00FF0FFFFFFFF00
000FFFFFFFFF000
00000FFFFF00000
}

sprite $queue [16x16/16] {
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
0FFFF0FFFF0000F0000F0000F0000F0
0FFFF0FFFF0000F0000F0000F0000F0
0FFFF0FFFF0000F0000F0000F0000F0
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
}


skinparam componentStyle uml2

node "xpublic" <<$exchange>> as xp {
 rectangle "q_shovel_tdd1" <<$queue>> as q00_0
 rectangle "q_shovel_tdd2" <<$queue>> as q00_1
}
node "xwinnow00" <<$exchange>> as xw00 {
 rectangle "q_winnow_t00_f10" <<$queue>> as q10_0
}
node "xwinnow01" <<$exchange>> as xw01 {
 rectangle "q_winnow_t01_f10" <<$queue>> as q10_1
}
node "xsarra" <<$exchange>> as xs {
 rectangle  "q_sarra_download_f20" <<$queue>> as q20
}
node "xflow_public" <<$exchange>> as xflow {
 rectangle  "q_subscribe_t_f30" <<$queue>> as q30
}
node "xs_tsource" <<$exchange>> as xsend {
 rectangle  "q_sender_tsource2send" <<$queue>> as q50
}
node "xs_tsource_output" <<$exchange>> as xout {
 rectangle  "q_subscribe_u_sftp_f60" <<$queue>> as q60
 rectangle  "q_subscribe_cp_f61" <<$queue>> as q61_0
}
node "xs_tsource_post" <<$exchange>> as xpost {
 rectangle  "q_poll_f62" <<$queue>> as q62
 rectangle  "q_subscribe_f70" <<$queue>> as q70
}
node "xs_tsource_poll" <<$exchange>> as xpoll {
 rectangle  "q_subscribe_f71" <<$queue>> as q71
}
node "xs_tsource_shim" <<$exchange>> as xshim

interface "t_dd1" as f00_0
interface "t_dd2" as f00_1
interface "t00_f10" as f10_0
interface "t01_f10" as f10_1
interface "download_f20" as f20
interface "t_f30" as f30
interface "f40" as f40
interface "u_sftp_f60" as f60
interface "cp_f61" as f61_0
interface "test2_f61" as f61_1
interface "f62" as f62
interface "f70" as f70
interface "f71" as f71
interface "shim_f63" as f63

' shovels
q00_0 --( f00_0
q00_1 --( f00_1
f00_0 -- xw00
f00_0 -- xw01
f00_1 -- xw00
f00_1 -- xw01

' winnows
q10_0 --( f10_0
q10_1 --( f10_1
f10_0 -- xs
f10_1 -- xs

' sarra
q20 --( f20
f20 -- xflow

' subscribe
q30 --( f30

' watch
f30 .. f40
f40 -- xsend

' sender
q50 --( f50
f50 -- xout

' subscribe
q60 --( f60
q61_0 --( f61_0
q70 --( f70
q71 --( f71

' post
f20 .. f61_1
f20 .. f63
f61_1 -- xpost
f63 -- xshim

' poll
q62 --( f62
f62 -- xpoll

legend right
Legend
|= |= Type |
| yellow dot| Sarracenia component     |
|      -(     | exchange interface|
|      -O     | post exchange interface|
|      ---    | filesystem interface   |
| rectangle| RabbitMQ queue |
| 3D rectangle   | RabbitMQ exchange |
endlegend
@enduml