.TH DD_Subscribe "1" "Oct 2013" "px 1.0.0" "Metpx suite"
.SH NAME
dd_subscribe \- Python program to select and download Environment Canada's datamart products
.SH SYNOPSIS
.B dd_subscribe \fI[-n]\fR \fIconfigfile.conf\fR
.SH DESCRIPTION
.PP
\fBdd.weather.gc.ca\fR is Environment Canada's website where a wide variety of meteorological products are
made available to the public. The website servers publish an amqp messages
containing the URL for each product posted as soon as it is available on the website.

\fBdd_subscribe\fR is a python program that uses python-pika to receive these amqp messages
and retrieve the web products and place them in a chosen local directory.

\fBdd_subscribe\fR takes one argument a configuration file. 
If you want \fBdd_subscribe\fR not to retrieve the products but only post the URL on standard
output, execute:   dd_subscribe -n config_file.  -n stands for "notify_only"

.PP
.SH CONFIGURATION
.PP
The configuration file is simple.
A comment is a line that begins with \fB#\fR. Empty lines are permitted.
To declare or set an option you simply use one of the form :
.nf

\fBoption <value>\fR

.fi
The specified defaults for all defined options below are valid and working (10/2013).

.SH RABBITMQ CREDENTIAL OPTIONS
Theses options set all the credential information to connect to the \fBRabbitMQ\fR 
server.
.nf


\fBhost     <hostname> (default: dd.weather.gc.ca)\fR
\fBport       <number> (default: 5672)\fR
\fBamqp_user    <user> (default: anonymous)\fR
\fBamqp_password  <pw> (default: anonymous)\fR


.fi
.SH AMQP EXCHANGE SETTINGS
Once connected to a RabbitMQ server, the user needs to set the \fBAMQP\fR exchanges.
Theses options define which messages (URL notifications) the program receives.
.nf


\fBexchange      <name>         (default: cmc)\fR
\fBexchange_type <type>         (default: topic)\fR
\fBexchange_key  <amqp pattern> (needs to be set)\fR


.fi
Several exchange_key options may be declared. To give a correct value to the exchange key,
browse the our website \fBhttp://dd.weather.gc.ca\fR and write down all directories of interest.
For each directories write an \fBexchange_key\fR option as follow:
.nf

\fBexchange_key  exp.dd.notify.directory1.*.subdirectory3.*.subdirectory5.#\fR

where  exp.dd.notify.   is a mandatory prefix
       *                replaces a directory name 
       #                stands for the remaining possibilities


.fi
.SH HTTP CREDENTIAL OPTIONS
Theses options set all the credential information for the http site.
It is unused for now but Environment Canada might implement some restricted
products in the future.
.nf


\fBhttp_user   <user> (default: None)\fR
\fBhttp_password <pw> (default: None)\fR


.fi
.SH DELIVERY SPECIFICATIONS
Theses options set what products the user wants and where it will be placed,
and under which name.
.nf


\fBlock      <.string>        (default: .tmp)\fR
\fBdirectory <path>           (default: .)\fR
\fBaccept    <regexp pattern> (must be set)\fR
\fBreject    <regexp pattern> (optional)\fR

\fBflatten   <boolean>        (default: false)\fR
\fBmirror    <boolean>        (default: false)\fR

.fi
.nf
The \fBlock\fR option is a suffix given to the file during the download
and taken away when it is completed... This gives a mean to avoid
processing the file prematurely.

The option directory  defines where to put the files on your server.
Combined with \fBaccept\fR/\fBreject\fR options, the user can select the
files of interest and their directories of residence. (see the \fBmirror\fR
option for more directory settings).


The \fBaccept\fR and \fBreject\fR options use regexp to match URL.
Theses options are processed sequentially. 
The URL of a product that match a \fBreject\fR pattern is never downloaded.
One that match an \fBaccept\fR pattern is downloaded into the directory
declared by the closest \fBdirectory\fR option above the matching \fBaccept\fR option.

ex.     directory /mylocaldirectory/myradars
        accept    .*RADAR.*

        directory /mylocaldirectory/mygribs
        reject    .*Reg.*
        accept    .*GRIB.*

The \fBmirror\fR option can be used to mirror the dd.weather.gc.ca tree of the products.
If set to \fBTrue\fR the directory given by the \fBdirectory\fR option
will be the basename of a tree. Accepted products under that directory will be
placed under the subdirectory tree leaf where it resides under dd.weather.gc.ca.
For example retrieving the following url, with options:

http://dd.weather.gc.ca/radar/PRECIP/GIF/WGJ/201312141900_WGJ_PRECIP_SNOW.gif

   mirror    True
   directory /mylocaldirectory
   accept    .*RADAR.*

would result in the creation of the directories and the file
/mylocaldirectory/radar/PRECIP/GIF/WGJ/201312141900_WGJ_PRECIP_SNOW.gif

The \fBflatten\fR option is use to set a separator character. This character
will be used to replace the '/' in the url directory and create a "flatten" filename
form its dd.weather.gc.ca path.  For example retrieving the following url, 
with options:

http://dd.weather.gc.ca/model_gem_global/25km/grib2/lat_lon/12/015/CMC_glb_TMP_TGL_2_latlon.24x.24_2013121612_P015.grib2

   flatten   -
   directory /mylocaldirectory
   accept    .*model_gem_global.*

would result in the creation of the filepath :

/mylocaldirectory/model_gem_global-25km-grib2-lat_lon-12-015-CMC_glb_TMP_TGL_2_latlon.24x.24_2013121612_P015.grib2

.fi
.SH PRODUCT QUEUING
When executed, \fBdd_subscribe\fR creates a queue name that should be unique.
It puts that name a file named ."configfile".queue . Normally \fBdd_subscribe\fR
would run like a deamon. If it is stopped, the messages (URL notifications) are queued.
Once reconnected, the downloads resume as expected.
You can run several dd_subscribe with different configuration files.
You can parallelize the download of products by running under the same user/directory
several dd_subscribe with the same configuration file.
Queues take resources onto our servers. We are running periodicaly a queue cleaner. 
A queue, unaccessed, for a long period (to be determined) will be destroyed.
A queue, unaccessed, with too much products (to be determined) will be destroyed.
.SH SARRACENIA
Just for fun, another rare, mostly carnivorous, canadian plant... (as sundew,columbo)
