.TH DD_Subscribe "1" "Oct 2013" "px 1.0.0" "Metpx-Sarracenia Suite"
.SH NAME
dd_subscribe \- Select and download Environment Canada's Datamart products
.SH SYNOPSIS
.B dd_subscribe \fI[-n]\fR \fIconfigfile.conf\fR
.SH DESCRIPTION
.PP
dd_subscribe is an efficient real-time file downloader, initially developed for \fBdd.weather.gc.ca\fR which is an Environment Canada website where a wide variety of meteorological products are
made available to the public. The website servers publish a message for each product as 
soon as it is available.  Clients subscribe to the notifications which use AMQP, a protocol 
that supports publish/subscribe communications patterns without the expensive polling 
involved in traditional ATOM/RSS schemes.

\fBdd_subscribe\fR takes one argument, a configuration file. 
If you want \fBdd_subscribe\fR not to retrieve the products but only post the URL on standard
output, execute:   dd_subscribe -n config_file.  -n stands for "notify_only" or "no_download"

.PP
.SH CONFIGURATION
.PP
Options are placed in the configuration file, one per line, of the form:
.nf

\fBoption <value>\fR

.fi
A comment is a line that begins with \fB#\fR. Empty lines are permitted.

.SH RABBITMQ CREDENTIAL OPTIONS
These options set all the credential information to connect to the \fBRabbitMQ\fR 
server.
.nf

	broker amqp{s}://<user>:<pw>@<brokerhost>[:port]/<vhost>
		(default: amqp://anonymous:anonymous@dd.weather.gc.ca/ ) 
		broken out: protocol,amqp-user,amqp-password,host,port,vhost

\fBhost     <hostname> (default: dd.weather.gc.ca)\fR
\fBport       <number> (default: 5672)\fR
\fBamqp-user    <user> (default: anonymous)\fR
\fBamqp-password  <pw> (default: anonymous)\fR


.fi
.SH AMQP QUEUE BINDINGS
Once connected to an AMQP broker, the user needs to create a queue and bind it
to an exchange.  These options define which messages (URL notifications) the program receives.
.nf

\fBexchange      <name>         (default: xpublic)\fR
\fBtopic_prefix  <amqp pattern> (default: v00.dd.notify -- developer option)\fR
\fBsubtopic      <amqp pattern> (topic or subtopic need to be set)\fR

.fi
Several topic options may be declared. To give a correct value to the subtopic,
browse the our website \fBhttp://dd.weather.gc.ca\fR and write down all directories of interest.
For each directories write an \fBsubtopic\fR option as follow:
.nf

\fBsubtopic  directory1.*.subdirectory3.*.subdirectory5.#\fR

where:  
       *                replaces a directory name 
       #                stands for the remaining possibilities

One has the choice of filtering using \fBsubtopic\fR with only AMQP's limited wildcarding, or the 
more powerful regular expression based \fBaccept/reject\fR mechanisms described below.  The 
difference being that the AMQP filtering is applied by the broker itself, saving the 
notices from being delivered to the client at all. The \fBaccept/reject\fR patterns apply to 
messages sent by the broker to the subscriber.  In other words, \fBaccept/reject\fR are 
client side filters, whereas \fBsubtopic\fR is server side filtering.  

It is best practice to use server side filtering to winnow out products to a small superset 
of what is relevant, and perform only a fine-tuning with the client side mechanisms, in order
to economize bandwidth and processing for all.

topic_prefix is primarily of interest during protocol version transitions, where one wishes to specify a non-default protocol version of messages to subscribe to. 

.fi

.SH AMQP QUEUE SETTINGS
The queue is where the notifications are held on the server for each subscriber.
.nf


\fBqueue         <name>         (default: None)\fR
\fBdurable       <boolean>      (default: False)\fR
\fBexpire        <minutes>      (default: None)\fR
\fBmessage-ttl   <minutes>      (default: None)\fR
\fBtimeout   <integer>        (default: 180)\fR


.fi
By default, dd_subscribe creates a queue name that should be unique and starts with \fBcmc\fR
and puts it into a file .<configname>.queue, where <configname> is the config filename.
The \fBqueue\fR option sets a queue name. It should always start with \fBcmc\fR.
The \fBexpire\fR option is expressed in minutes... it sets how long should live
a queue without connections The \fBdurable\fR option set to True, means writes the queue
on disk if the broker is restarted.
The \fBmessage-ttl\fR option set the time in minutes a message can live in the queue.
Past that time, the message is taken out of the queue by the broker.
.SH HTTP DOWNLOAD CREDENTIALS 
.nf

\fBhttp-user   <user> (default: None)\fR
\fBhttp-password <pw> (default: None)\fR

.fi
.SH DELIVERY SPECIFICATIONS
Theses options set what products the user wants and where it will be placed,
and under which name.
.nf


\fBaccept    <regexp pattern> (must be set)\fR
\fBdirectory <path>           (default: .)\fR
\fBflatten   <boolean>        (default: false)\fR
\fBlock      <.string>        (default: .tmp)\fR
\fBmirror    <boolean>        (default: false)\fR
\fBoverwrite <boolean>        (default: true)\fR
\fBreject    <regexp pattern> (optional)\fR

.fi
.nf
The \fBlock\fR option is a suffix given to the file during the download
and taken away when it is completed... If \fBlock\fR is set to \fB.\fR
then it is prefixed with it and taken away when it is completed...
This gives a mean to avoid processing the file prematurely.

The option directory  defines where to put the files on your server.
Combined with \fBaccept\fR/\fBreject\fR options, the user can select the
files of interest and their directories of residence. (see the \fBmirror\fR
option for more directory settings).


The \fBaccept\fR and \fBreject\fR options use regular expressions (regexp) to match URL.
Theses options are processed sequentially. 
The URL of a product that match a \fBreject\fR pattern is never downloaded.
One that match an \fBaccept\fR pattern is downloaded into the directory
declared by the closest \fBdirectory\fR option above the matching \fBaccept\fR option.

ex.     directory /mylocaldirectory/myradars
        accept    .*RADAR.*

        directory /mylocaldirectory/mygribs
        reject    .*Reg.*
        accept    .*GRIB.*

The \fBmirror\fR option can be used to mirror the dd.weather.gc.ca tree of the products.
If set to \fBTrue\fR the directory given by the \fBdirectory\fR option
will be the basename of a tree. Accepted products under that directory will be
placed under the subdirectory tree leaf where it resides under dd.weather.gc.ca.
For example retrieving the following url, with options:

http://dd.weather.gc.ca/radar/PRECIP/GIF/WGJ/201312141900_WGJ_PRECIP_SNOW.gif

   mirror    True
   directory /mylocaldirectory
   accept    .*RADAR.*

would result in the creation of the directories and the file
/mylocaldirectory/radar/PRECIP/GIF/WGJ/201312141900_WGJ_PRECIP_SNOW.gif

The \fBflatten\fR option is use to set a separator character. This character
will be used to replace the '/' in the url directory and create a "flatten" filename
form its dd.weather.gc.ca path.  For example retrieving the following url, 
with options:

http://dd.weather.gc.ca/model_gem_global/25km/grib2/lat_lon/12/015/CMC_glb_TMP_TGL_2_latlon.24x.24_2013121612_P015.grib2

   flatten   -
   directory /mylocaldirectory
   accept    .*model_gem_global.*

would result in the creation of the filepath :

/mylocaldirectory/model_gem_global-25km-grib2-lat_lon-12-015-CMC_glb_TMP_TGL_2_latlon.24x.24_2013121612_P015.grib2


The \fBtimeout\fR option is use to set a time limit to the file download, avoiding network freeze.
If a download takes more than \fBtimeout\fR seconds, the download is restarted. This looping continues
until the file is properly downloaded... Only than, the amqp message is acknowledge.

The \fBoverwrite\fR option,if set to false, avoid unnecessary downloads under these conditions :
1- the file to be downloaded is already on the user's file system at the right place and
2- the checksum of the amqp message matched the one of the file.
The default is True (overwrite without checking).

.fi
.SH PRODUCT QUEUING
When executed, \fBdd_subscribe\fR creates a queue name that should be unique.
It puts that name a file named ."configfile".queue . Normally \fBdd_subscribe\fR
would run like a deamon. If it is stopped, the messages (URL notifications) are queued.
Once reconnected, the downloads resume as expected.
You can run several dd_subscribe with different configuration files.
You can parallelize the download of products by running under the same user/directory
several dd_subscribe with the same configuration file.
Queues take resources onto our servers. We are running periodicaly a queue cleaner. 
A queue, unaccessed, for a long period (to be determined) will be destroyed.
A queue, unaccessed, with too much products (to be determined) will be destroyed.

.SH DEPRECATED Settings
\fBexchange_type <type>         (default: topic)\fR
\fBexchange_key  <amqp pattern> (deprecated)\fR


.SH NOTES

SARRACENIA -- Just for fun, another rare, mostly carnivorous, canadian plant... (as sundew,columbo)

\fBdd_subscribe\fR is a python program that uses python-amqplib to receive these amqp messages
and optionally retrieve the web products and place them in a chosen local directory.

http://metpx.sf.net/ - dd_subscribe is a component of MetPX-Sarracenia, the AMQP based file switch.
