name: sr_insects test basic declare/cleanup, and python API

on:
  pull_request:
    types: [opened, edited, reopened]
  push:

  workflow_dispatch:

jobs:

  run_sr_insects_tests:

    strategy:
      # Don't cancel the entire matrix when one job fails
      fail-fast: false
      matrix:
       osver: [ "ubuntu-20.04", "ubuntu-22.04" ]

    runs-on: ${{ matrix.osver }}
  
    name: Maintenance test on ${{ matrix.osver }}
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          travis/flow_autoconfig.sh
          travis/ssh_localhost.sh
         
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event.inputs.debug_enabled }}
        #if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Add and Remove configs, 
        run: |
          pwd
          ls
          cd ${HOME}/sr_insects/static_flow; ./flow_maint_test.sh
