name: sr_insects test basic declare/cleanup, and python API

on:
  pull_request:
    types: [opened, edited, reopened]
  push:
    paths-ignore:
      - '.github/**'
      - 'debian/changelog'
      - 'TODO.txt'


  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:

  run_sr_insects_tests:

    strategy:
      # Don't cancel the entire matrix when one job fails
      fail-fast: false
      matrix:
       osver: [ "ubuntu-20.04", "ubuntu-22.04", "ubuntu-24.04" ]

    runs-on: ${{ matrix.osver }}
  
    name: Maintenance test on ${{ matrix.osver }}
    timeout-minutes: 20
    
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          travis/flow_autoconfig.sh
          travis/ssh_localhost.sh
         
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Add and Remove configs, 
        run: |
          pwd
          ls
          cd ${HOME}/sr_insects/static_flow; ./flow_maint_test.sh
