---
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Build container image: sarracenia"

on:
  push:
    branches:
      - development
    tags:
      # stable versions are built from tags
      # does not include rc tags
      - 'v[0-9]+.[0-9]+.[0-9]+'
      # exclude v2 tags
      - '!v2.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sarracenia

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          # need full git history to get tags
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          # all images get tagged with 'latest'
          # images built from the development branch gets tagged 'development'
          # images built from tags will get tagged 'stable' and a tag matching the version (without the v prefix)
          tags: |
            type=raw,value=latest
            type=raw,value=development,enable=${{ github.ref == 'refs/heads/development' }}
            type=raw,value=stable,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
