name: Python package

on:
  pull_request:
    types: [opened, edited, reopened]
  push:
    branches:
    - v03_wip

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        osver: [ "ubuntu-20.04", "ubuntu-22.04" ]
    
    runs-on: ${{ matrix.osver }}
  
    name: Unit test on ${{ matrix.osver }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Test with pytest
        run: |
          pytest tests --junitxml=tests/junit/test-results.xml \
            --cov-config=tests/.coveragerc --cov=sarracenia --cov-report=html --cov-report=lcov \
            --html=tests/report.html --self-contained-html

      - name: Upload pytest junit results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.osver }}
          path: tests/junit/test-results.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      
      - name: Upload pytest HTML report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ matrix.osver }}
          path: tests/report.html
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      
      - name: Upload code coverage report (HTML)
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ matrix.osver }}
          path: tests/coverage/html_report
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      - name: Upload code coverage report (LCOV)
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ matrix.osver }}
          path: tests/coverage/coverage.lcov
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}