name: v2 sr_insects Flow Tests.

on:
  pull_request:
    types: [opened, edited, reopened]
  push:
    branches:
      - v2_dev
      - v2_stable

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

env:
   sarra_py_version: 2.22
   V2_SKIP_KNOWN_BAD: yes
   SKIP_KNOWN_BAD: yes

jobs:

  run_sr_insects_tests:

    strategy:
      # Don't cancel the entire matrix when one job fails
      fail-fast: false
      matrix:
       which_test: [ static_flow, flakey_broker, dynamic_flow ]
       osver: [ "ubuntu-18.04", "ubuntu-20.04", "ubuntu-22.04" ]

    runs-on: ${{ matrix.osver }}
  
    name: ${{ matrix.which_test }} test on ${{ matrix.osver }}
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          travis/flow_autoconfig.sh
          travis/ssh_localhost.sh
         
      - name: Setup ${{ matrix.which_test }} test.
        run: |
          cd ${HOME}; pwd; ls ; echo "testing sarra version: $sarra_py_version"
          cd ${HOME}/sr_insects/${{ matrix.which_test }}; ./flow_setup.sh

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      # https://github.com/marketplace/actions/debugging-with-tmate
      # 
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      #  #if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Limit ${{ matrix.which_test }} test.
        run: |
          cd ${HOME}/sr_insects/${{ matrix.which_test }}; ./flow_limit.sh

      - name: Check results of ${{ matrix.which_test }} test.
        run: |
          cd ${HOME}/sr_insects/${{ matrix.which_test }}; ./flow_check.sh
        
      - name: Compress log files for artifacts
        if: always()
        continue-on-error: true
        run: |
          sr stop
          cd ${HOME}/.cache/sarra/log/
          tar -czf ${HOME}/logs.tar.gz *
      
      - name: Save run artifacts
        if: always()
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: SarraV2_${{ matrix.which_test }}_${{ matrix.osver }}_logs_${{ github.sha }}
          path: ~/logs.tar.gz
